import html as html_module
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

e = html_module.escape


def _render_html(payload: dict) -> str:
    base = Path(__file__).resolve().parent / "templates"
    css = (base / "report.css").read_text()
    template = (base / "report.html").read_text()

    session = payload.get("session", {})
    project = payload.get("project", {})
    industries = payload.get("industries", [])
    papers = payload.get("papers", [])
    analyses = payload.get("analyses", [])
    gaps = payload.get("gaps", {})
    ideas = payload.get("ideas", [])

    content = [
        "<h1>Whitespace Research Synthesis Report</h1>",
        "<div class='meta'>",
        f"<div>Project: {e(str(project.get('name') or 'Unknown'))}</div>",
        f"<div>Session ID: {e(str(session.get('id') or ''))}</div>",
        f"<div>Status: {e(str(session.get('status') or ''))}</div>",
        f"<div>Runner: {e(str(session.get('runner_used') or 'Unknown'))}</div>",
        "</div>",
    ]

    if industries:
        content.append("<div class='section'><h2>Industries</h2>")
        for industry in industries:
            content.append(
                f"<div class='card'><strong>{e(str(industry.get('name') or ''))}</strong><br />"
                f"{e(str(industry.get('description') or ''))}</div>"
            )
        content.append("</div>")

    if papers:
        content.append("<div class='section'><h2>Papers</h2><ul>")
        for paper in papers:
            title = e(str(paper.get("title") or "Untitled"))
            source = e(str(paper.get("source_type") or ""))
            content.append(f"<li>{title} ({source})</li>")
        content.append("</ul></div>")

    if analyses:
        content.append("<div class='section'><h2>Paper Analyses</h2>")
        for analysis in analyses:
            content.append(f"<h3>Paper {e(str(analysis.get('paper_id') or ''))}</h3>")
            if analysis.get("summary"):
                content.append(f"<p>{e(str(analysis['summary']))}</p>")
            if analysis.get("key_claims"):
                content.append("<strong>Key Claims</strong><ul>")
                for claim in analysis["key_claims"]:
                    content.append(f"<li>{e(str(claim))}</li>")
                content.append("</ul>")
        content.append("</div>")

    content.append("<div class='section'><h2>Gap Map</h2>")
    if gaps.get("engineering_gaps"):
        content.append("<strong>Engineering Gaps</strong><ul>")
        for gap in gaps["engineering_gaps"]:
            content.append(f"<li>{e(str(gap))}</li>")
        content.append("</ul>")
    if gaps.get("ready_to_productize"):
        content.append("<strong>Ready to Productize</strong><ul>")
        for item in gaps["ready_to_productize"]:
            content.append(f"<li>{e(str(item))}</li>")
        content.append("</ul>")
    if gaps.get("recurring_pain_points"):
        content.append("<strong>Recurring Pain Points</strong><ul>")
        for point in gaps["recurring_pain_points"]:
            content.append(f"<li>{e(str(point))}</li>")
        content.append("</ul>")
    content.append("</div>")

    if ideas:
        content.append("<div class='section'><h2>Synthesized Ideas</h2>")
        for idea in ideas:
            content.append("<div class='card'>")
            content.append(f"<h3>{e(str(idea.get('title') or ''))}</h3>")
            if idea.get("description"):
                content.append(f"<p>{e(str(idea['description']))}</p>")
            content.append(
                f"<div>Scores: Novelty {e(str(idea.get('novelty_score', '')))} · "
                f"Feasibility {e(str(idea.get('feasibility_score', '')))}</div>"
            )
            if idea.get("industry_assessments"):
                content.append("<strong>Industry Assessments</strong><ul>")
                for assessment in idea["industry_assessments"]:
                    content.append(
                        f"<li>{e(str(assessment.get('industry_name') or ''))}: "
                        f"{e(str(assessment.get('applicability_score') or ''))} — "
                        f"{e(str(assessment.get('applicability_description') or ''))}</li>"
                    )
                content.append("</ul>")
            content.append("</div>")
        content.append("</div>")

    content.append("<div class='footer'>Generated by Whitespace</div>")

    return template.replace("{{css}}", css).replace("{{content}}", "\n".join(content))


def export_pdf(payload: dict, out_path: str) -> None:
    try:
        from weasyprint import HTML

        HTML(string=_render_html(payload)).write_pdf(out_path)
    except (ImportError, OSError) as exc:
        logger.warning("PDF export unavailable (pango/weasyprint not configured): %s", exc)
        with open(out_path, "w") as f:
            f.write("PDF export unavailable — install pango: brew install pango")
