import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def _render_html(payload: dict) -> str:
    base = Path(__file__).resolve().parent / "templates"
    css = (base / "report.css").read_text()
    template = (base / "report.html").read_text()

    session = payload.get("session", {})
    project = payload.get("project", {})
    industries = payload.get("industries", [])
    papers = payload.get("papers", [])
    analyses = payload.get("analyses", [])
    gaps = payload.get("gaps", {})
    ideas = payload.get("ideas", [])

    content = [
        "<h1>Whitespace Research Synthesis Report</h1>",
        "<div class='meta'>",
        f"<div>Project: {project.get('name') or 'Unknown'}</div>",
        f"<div>Session ID: {session.get('id')}</div>",
        f"<div>Status: {session.get('status')}</div>",
        f"<div>Runner: {session.get('runner_used') or 'Unknown'}</div>",
        "</div>",
    ]

    if industries:
        content.append("<div class='section'><h2>Industries</h2>")
        for industry in industries:
            content.append(
                f"<div class='card'><strong>{industry.get('name')}</strong><br />"
                f"{industry.get('description')}</div>"
            )
        content.append("</div>")

    if papers:
        content.append("<div class='section'><h2>Papers</h2><ul>")
        for paper in papers:
            title = paper.get("title") or "Untitled"
            content.append(f"<li>{title} ({paper.get('source_type')})</li>")
        content.append("</ul></div>")

    if analyses:
        content.append("<div class='section'><h2>Paper Analyses</h2>")
        for analysis in analyses:
            content.append(f"<h3>Paper {analysis.get('paper_id')}</h3>")
            if analysis.get("summary"):
                content.append(f"<p>{analysis['summary']}</p>")
            if analysis.get("key_claims"):
                content.append("<strong>Key Claims</strong><ul>")
                for claim in analysis["key_claims"]:
                    content.append(f"<li>{claim}</li>")
                content.append("</ul>")
        content.append("</div>")

    content.append("<div class='section'><h2>Gap Map</h2>")
    if gaps.get("gaps"):
        content.append("<strong>Gaps</strong><ul>")
        for gap in gaps["gaps"]:
            content.append(f"<li>{gap}</li>")
        content.append("</ul>")
    if gaps.get("contradictions"):
        content.append("<strong>Contradictions</strong><ul>")
        for contradiction in gaps["contradictions"]:
            content.append(f"<li>{contradiction}</li>")
        content.append("</ul>")
    if gaps.get("recurring_themes"):
        content.append("<strong>Recurring Themes</strong><ul>")
        for theme in gaps["recurring_themes"]:
            content.append(f"<li>{theme}</li>")
        content.append("</ul>")
    content.append("</div>")

    if ideas:
        content.append("<div class='section'><h2>Synthesized Ideas</h2>")
        for idea in ideas:
            content.append("<div class='card'>")
            content.append(f"<h3>{idea.get('title')}</h3>")
            if idea.get("description"):
                content.append(f"<p>{idea['description']}</p>")
            content.append(
                f"<div>Scores: Novelty {idea.get('novelty_score')} · "
                f"Feasibility {idea.get('feasibility_score')}</div>"
            )
            if idea.get("industry_assessments"):
                content.append("<strong>Industry Assessments</strong><ul>")
                for assessment in idea["industry_assessments"]:
                    content.append(
                        f"<li>{assessment.get('industry_name')}: "
                        f"{assessment.get('applicability_score')} — "
                        f"{assessment.get('applicability_description')}</li>"
                    )
                content.append("</ul>")
            content.append("</div>")
        content.append("</div>")

    content.append("<div class='footer'>Generated by Whitespace</div>")

    return template.replace("{{css}}", css).replace("{{content}}", "\n".join(content))


def export_pdf(payload: dict, out_path: str) -> None:
    try:
        from weasyprint import HTML

        HTML(string=_render_html(payload)).write_pdf(out_path)
    except (ImportError, OSError) as exc:
        logger.warning("PDF export unavailable (pango/weasyprint not configured): %s", exc)
        with open(out_path, "w") as f:
            f.write("PDF export unavailable — install pango: brew install pango")
